# Generated by Django 3.2.9 on 2021-11-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getFile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='file_content',
        ),
    ]
